### ISSUE TITLE
panic with Go 1.6

### ISSUE THREAD

**Issue by dshills** [fsnotify/fsevents#12]
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x4152820, 0xc82000a5b0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/fsnotify/fsevents.(*EventStream).Start(0xc82001c240)
        /Users/dshills/Development/Go/src/github.com/fsnotify/fsevents/fsevents.go:213 +0x826
github.com/dshills/goauto.(*watchOSX).Start(0xc820016630, 0x11e1a300, 0xc820010520, 0x2, 0x2, 0x0, 0x0, 0x0)

After installing Go 1.6 all apps using fsevents panic on startup with this error.

**Comment by wadey** [comment]
This document describes a solution to this issue: https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md

> A particular unsafe area is C code that wants to hold on to Go func and pointer values for future callbacks from C to Go. This works today but is not permitted by the invariant. It is hard to detect. One safe approach is: Go code that wants to preserve funcs/pointers stores them into a map indexed by an int. Go code calls the C code, passing the int, which the C code may store freely. When the C code wants to call into Go, it passes the int to a Go function that looks in the map and makes the call. An explicit call is required to release the value from the map if it is no longer needed, but that was already true before.

I'll try to work on a pull request for this.

**Comment by nathany** [comment]
Thanks for reporting the issue @dshills. A PR would be great, thanks @wadey.

Fyi, this looks like it may be the same issue as in notify: https://github.com/rjeczalik/notify/issues/90

**Comment by wadey** [comment]
I opened a PR with a potential fix here: https://github.com/fsnotify/fsevents/pull/13
