### ISSUE TITLE
integrating into fsnotify

### ISSUE THREAD

**Issue by drewwells** [fsnotify/fsevents#14]
Any plans to wrap these low functions into a fsnotify interface?

The biggest things (to me) is the lack of an event channel and simplifying the exposed flags to those exposed by fsnotify.

**Comment by nathany** [comment]
Yes. I'm not sure how it will work.

FSEvents watches trees recursively whereas fsnotify does not.

**Comment by drewwells** [comment]
Not sure I follow. I watch files recursively with fsnotify. It's been a while, so perhaps I'm registering each file individually with fsnotify.

Still good point, I noticed this behavior when I integrated https://github.com/wellington/wellington/pull/183

Instead of exposing the raw eventstream, the event path would be evaluated against the paths that were requested. If an event path matches one of the paths being watched, then it notifies via a channel to the consumer.

**Comment by drewwells** [comment]
Checked the fsnotify, yeah the API only exposes non-recursive watching. Not terrific, it would be nice to get recursive watching. The point is eventually to merge these two packages... isn't it?

**Comment by nathany** [comment]
Yah, merge or more likely have fsnotify depend on the fsevents package. Though probably all within a single repository.

I'm not sure if we *need* fsnotify to do recursive watches for other platforms, it just means the behaviour would be different.

Here are some related issues on fsnotify:

user-space recursive watches https://github.com/fsnotify/fsnotify/issues/18
FSEvents https://github.com/fsnotify/fsnotify/issues/11

It might be interesting to expose kqueue, FSEvents, inotify, etc. as drivers that all behave a bit differently. Then layer on top of that (optional) features to make them more compatible with each other.

**Comment by drewwells** [comment]
on top of watching trees, there are editors that do not trigger file events with the vanilla fsnotify. What blockers are there currently at getting native fsevents in fsnotify?

**Comment by samjacobson** [comment]
I like the idea of multiple drivers. Perhaps these drivers could expose flags to the core fsnotify informing of their features (e.g. "supports recursive watching", "only recursive", "max handles", etc). Then the core fsnotify can implement (fake up) any features requested by the application not supported by the driver including advanced pattern matching etc.

The reason I like this idea is that the drivers needn't support just the "lowest common denominator" of features, they can support as much as is available. Applications can then access the lowest common denominator of features of all drivers via fsnotify (and those features that can be layered on top). If absolutely necessary an application can still access the driver directly for platform specific optimisations.

**Comment by nathany** [comment]
Maybe it could be a bit like building a middleware stack like my old pipeline ideas. You could start with the raw drivers and layer things on somehow until everything behaves more-or-less the same. Or you could just grab a good default that has the layers applied.

We also need to dramatically improve the testing story for fsnotify. I'd like to build out a selection of custom test helpers that can be used for checking and verifying various scenarios. For the low-level tests, I like the idea of golden files mentioned at https://www.youtube.com/watch?v=yszygk1cpEc.

**Comment by drewwells** [comment]
I do like the idea of supporting all available features everywhere, and
that would be pretty awesome for implementers. I do worry this would make
the API onerous. How do recursive watchers work when the driver doesn't
support them?

At least for a first pass, I'd like to break out the current implementation
of fsnotify into a separate drivers (if it isn't already) then add fsevents
as a driver. The API would expose the same API that's in use now, even if
the driver supports additional features. This would be a good baseline to
start implementing additional features like recursive watchers specific OS
restrictions, etc.

**Comment by samjacobson** [comment]
> I do like the idea of supporting all available features everywhere, and
that would be pretty awesome for implementers. I do worry this would make
the API onerous. How do recursive watchers work when the driver doesn't
support them?

I think fsnotify core has 2 potential responses when an application asks to recursively monitor a directory:
1. Return an error OS_NOT_SUPPORTED
2. Fake recursive watching by implementing as a layer on top of the driver

I have a bias with recursive watching, but there are lots of features that are OS specific, and I'm not advocating including them all in the main API. Perhaps just a select few (like recursive watching) because they are generally useful. Anything else that is OS specific, but not (arguably) generally useful and/or impossible to fake should be implemented in the driver, but not exposed by fsnotify. If has application has a use for those OS specific features it can always use the driver directly.

**Comment by drewwells** [comment]
This sounds good. I'm excited where do we get started? Maybe describing a
2.0 interface then start filling in the gaps in various drivers?

**Comment by samjacobson** [comment]
Once we have a driver API I can reshape FSEvents to fit it.

I haven't watched that video yet @nathany , but perhaps the driver abstraction will assist with testing. If fsnotify core doesn't do any actual file system monitoring then it should be easy to test? Each driver can then be tested from the driver API. Many tests are probably generic between drivers, with platform specific tests for platform specific features.

**Comment by nathany** [comment]
@drewwells I still think the place to get started is having more than zero tests for fsevents.

But maybe we should first move fsevents into a subfolder of fsnotify so we can write and share test helpers.

@samjacobson I agree. At least in theory, user-space layers should be testable in isolation with hitting the underlying drivers.

The concept of golden files is simply to record what happens using a flag (eg. `go test -update`) and then compare subsequent runs to that output to ensure behaviour doesn't change.

**Comment by drewwells** [comment]
@nathany sounds good to focus on tests, that will make refactors much easier. @samjacobson I agree, that's a good way to test the application code. Testing fsevents directly would be redundant to the tests already present in fsevents itself.

**Comment by nathany** [comment]
I proposed an x/fsn library that sits between fsnotify and syscall. If that happens, I would expect this repository to be the basis for the FSEvents support.

https://github.com/golang/go/issues/15406

A cross-platform fsnotify interface is a hard problem. I think makes sense to address it independently of getting the low-level parts solid, and possibly in a variety of ways to see what works best.

**Comment by nathany** [comment]
An update to my last post. 

I'd still like to split out low-level libraries from fsnotify (https://github.com/fsnotify/fsnotify/issues/75), likely starting with inotify for Linux (https://github.com/fsnotify/fsnotify/issues/173). But I'm no longer proposing that it be part of the Go project based on the discussion at https://github.com/golang/go/issues/17244.

This could take a while -- but once done, it should put us in a better spot for substituting in FSEvents on macOS. 🙏
