### ISSUE TITLE
Go 1.10 support

### ISSUE THREAD

**Issue by drewwells** [fsnotify/fsevents#33]
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which version of macOS are you using?
```
-> % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A365
```

### Please describe the issue that occurred.
building on Go 1.10 introduces build errors

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

```
-> % GOROOT=/usr/local/go110 /usr/local/go110/bin/go test
# github.com/fsnotify/fsevents
./wrap.go:38: constant 36893488147419103231 overflows uint64
./wrap.go:80: cannot use f (type FSEventStreamRef) as type _Ctype_ConstFSEventStreamRef in argument to func literal
./wrap.go:85: cannot use f (type FSEventStreamRef) as type _Ctype_ConstFSEventStreamRef in argument to func literal
./wrap.go:91: cannot use f (type FSEventStreamRef) as type _Ctype_ConstFSEventStreamRef in argument to func literal
./wrap.go:97: cannot use f (type FSEventStreamRef) as type _Ctype_ConstFSEventStreamRef in argument to func literal
./wrap.go:112: cannot convert nil to type _Ctype_CFUUIDRef
./wrap.go:115: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
./wrap.go:119: cannot convert nil to type _Ctype_CFStringRef
./wrap.go:122: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
./wrap.go:175: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCString
./wrap.go:175: too many errors
```

Go 1.10 is still in beta1. Based on the release notes, I can't see why the implicit conversion to C to _Ctype is failing now.

**Comment by bep** [comment]
Since this build fine on some macOS'es (see Travis: https://travis-ci.org/gohugoio/hugo/jobs/324420193) I would guess that this is a High Sierra thing -- and you should really consider reporting this on the Go issue tracker.

**Comment by bep** [comment]
I created this issue just in case:

https://github.com/golang/go/issues/23317

**Comment by nilleb** [comment]
In the golang issue they have pointed out this page: https://tip.golang.org/doc/go1.10#cgo

**Comment by wadey** [comment]
I've opened a PR here: #34
