### ISSUE TITLE
wrap.go ignores failure return value from FSEventStreamStart

### ISSUE THREAD

**Issue by nicks** [fsnotify/fsevents#37]
While investigating https://github.com/fsnotify/fsevents/issues/36, I noticed that this package ignores the failure return value from FSEventStreamStart

https://developer.apple.com/documentation/coreservices/1448000-fseventstreamstart

```
Return Value

True if it succeeds, otherwise False if it fails. It ought to always succeed, but in the event it does not then your code should fall back to performing recursive scans of the directories of interest as appropriate.
```

The linked bug is an example of a case where it returns false. This failure should be propagated to the caller somehow.

**Comment by pbnjay** [comment]
I have a "fix" for this that adds an `error` return value to both `Start()` and `Restart()`
I will include an automated test for #48 to make sure there is good test coverage.
