### ISSUE TITLE
fsevents/go_1_10_after.go:6:10: fatal error: 'CoreServices/CoreServices.h' file not found

### ISSUE THREAD

**Issue by brilllc** [fsnotify/fsevents#45]
go get github.com/fsnotify/fsevents

# github.com/fsnotify/fsevents
../../github.com/fsnotify/fsevents/go_1_10_after.go:6:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

help me

**Comment by havoc-io** [comment]
@brilllc Do you have Xcode and/or the relevant macOS toolchains/SDKs installed?  My naïve guess would be that they're missing from the system where you're trying to build the package.  You can install the basic Xcode command line tools (without Xcode) using:

    xcode-select --install

I *believe* this also installs the SDK for the version of macOS that you're using, but I'm not 100% sure.

**Comment by nathany** [comment]
Thanks @havoc-io. We should probably mention this in the README.
