### ISSUE TITLE
Support build on darwin_arm64 with cgo

### ISSUE THREAD

**Issue by mistic** [fsnotify/fsevents#50]
@nathany I'm trying to use `fsevents` as a dependency of a go binary that I want to build for `darwin_arm64` with `cgo` from a `darwin_amd64` host. However I got the following

```
external/go_sdk/pkg/tool/darwin_amd64/link: running external/local_config_cc/cc_wrapper.sh failed: exit status 134
ld: warning: ignoring file /var/folders/bz/z6hcm0ys1c922kw4v137vh9c0000gn/T/go-link-3522633666/000005.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file /var/folders/bz/z6hcm0ys1c922kw4v137vh9c0000gn/T/go-link-3522633666/000006.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
ld: warning: ignoring file /var/folders/bz/z6hcm0ys1c922kw4v137vh9c0000gn/T/go-link-3522633666/000007.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
Undefined symbols for architecture arm64:
  "__cgo_45b9ffab6b40_Cfunc_ArrayCreateMutable", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_ArrayCreateMutable in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFArrayAppendValue", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFArrayAppendValue in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFRelease", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFRelease in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFRetain", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFRetain in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFRunLoopGetCurrent", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFRunLoopGetCurrent in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFRunLoopRun", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFRunLoopRun in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFRunLoopStop", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFRunLoopStop in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFStringCreateCopy", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFStringCreateCopy in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFStringCreateWithCString", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFStringCreateWithCString in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFStringGetBytes", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFStringGetBytes in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFStringGetLength", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFStringGetLength in go.o
  "__cgo_45b9ffab6b40_Cfunc_CFUUIDCreateString", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_CFUUIDCreateString in go.o
  "__cgo_45b9ffab6b40_Cfunc_EventStreamCreate", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_EventStreamCreate in go.o
  "__cgo_45b9ffab6b40_Cfunc_EventStreamCreateRelativeToDevice", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_EventStreamCreateRelativeToDevice in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamFlushAsync", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamFlushAsync in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamFlushSync", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamFlushSync in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamInvalidate", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamInvalidate in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamRelease", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamRelease in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamScheduleWithRunLoop", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamScheduleWithRunLoop in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamStart", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamStart in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventStreamStop", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventStreamStop in go.o
  "__cgo_45b9ffab6b40_Cfunc_FSEventsCopyUUIDForDevice", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_FSEventsCopyUUIDForDevice in go.o
  "__cgo_45b9ffab6b40_Cfunc__Cmalloc", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc__Cmalloc in go.o
  "__cgo_45b9ffab6b40_Cfunc_free", referenced from:
      _github.com/fsnotify/fsevents._cgo_45b9ffab6b40_Cfunc_free in go.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
external/local_config_cc/cc_wrapper.sh: line 69: 69609 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
```

I think this is coming from https://github.com/fsnotify/fsevents/blob/master/wrap.go#L6

Could you please give an help here to fix the problem?

For reference what I'm trying to build is https://github.com/bazelbuild/bazel-watcher which depends on `fsnotify/fsevents`

**Comment by nathany** [comment]
@mistic I'm not sure what to make of this error message. Probably need to dig into Apple's documentation.

**Comment by mistic** [comment]
@nathany I believe the function on the error is being imported from the `CoreServices` framework. I dont have experience on those, but Is it possible it is not available for darwin arm64 architecture or that we need to update any compiler tooling to support it ?

**Comment by nathany** [comment]
Do you have Rosetta 2 installed on your Mac?

With go 1.17.5, I am not seeing any build errors on an M1, but timeouts or just running forever when running `go test`.

```
❯ go test


^Csignal: interrupt
FAIL	github.com/fsnotify/fsevents	333.003s
```

At some point we probably need to get a failing test in place.

Unfortunately I don't think Travis CI or GitHub Actions support Apple Silicon yet. 
https://github.com/actions/virtual-environments/issues/2187
But we can run the tests locally (once we sort out the timeout issue).

What are others seeing on M1, and what steps to reproduce?

**Comment by mistic** [comment]
@nathany in order to cross compile the bazel-watcher lib in a Mac Intel for a Apple silicon just do the following:

1 - install bazelisk (https://github.com/bazelbuild/bazelisk)
2 - checkout bazel-watcher ( https://github.com/bazelbuild/bazel-watcher )
3 - cherry-pick https://github.com/bazelbuild/bazel-watcher/pull/490/commits/1a3abc76cff64f4104deccad266284cf6d54cb5f or just apply the changes manually in order to get go >= 1.17 which is needed for apple silicon
4 - run `bazel build //ibazel:ibazel --config release --platforms=@io_bazel_rules_go//go/toolchain:darwin_arm64_cgo`

You should now get the fsevents related error I reported above 😃

**Comment by pbnjay** [comment]
This appears to be a misconfiguration in bazel et al.

@mistic I wasn't able to get those instructions to work (I checked out the parent commit and copied WORKSPACE from your linked patch, but the error is something about --incompatible_use_cc_configure_from_rules_cc)

This log line makes it look like CGO isn't compiling to the right arch: `building for macOS-arm64 but attempting to link with file built for unknown-x86_64` Can you dump bazel's environment? I suspect it's not setting GOARCH correctly or something. Sorry I'm not familiar with bazel enough to trace the build process.

I don't have an M1 to confirm, but cross-compiling using the Go toolchain works fine for me on an Intel mac:
```
$ cd $GOPATH/src/github.com/fsnotify/fsevents
$ cd example
$ GOARCH=arm64 CGO_ENABLED=1 go build .
$ file example
example: Mach-O 64-bit executable arm64
```

**Comment by mistic** [comment]
@pbnjay could you please create a `.bazelversion` at the root of the checkout like https://github.com/bazelbuild/bazelisk/blob/master/.bazelversion so it assures you run an updated version of bazel (I forgot to mention this, sorry)? 

> This log line makes it look like CGO isn't compiling to the right arch

The command I sent to build makes sure it builds for the correct architecture but something with the cgo compilation involving fsevents is not working. When you run a go compilation on Bazel both goarch or cgo could be managed by the `--platforms` flag. More info at: https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/rules.md#go_binary and https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/cross_compilation.md#cross-compilation

**Comment by pbnjay** [comment]
Still no luck with that change. I am able to build with "darwin_amd64_cgo" just fine, so this is definitely something with the arm64 bazel toolchain. Again, I don't have much experience with bazel, but I don't think it's appropriate to debug issues in that significantly more complex package in this space.

After a quick search, I see you can get the executed compiler commands from bazel, so please try `bazel build --subcommands ...` and make sure that GOARCH and arm64-related paths are being correctly used.

**Comment by bep** [comment]
For what it's worth, we use `fsnotify` in Hugo and we do build for Darwin arm64 with CGO (and we do cross compilation, too). Heck, I'm sitting on a brand new 14 inch M1 MacBook as we speak.

**Comment by mistic** [comment]
@pbnjay I was really convinced the problem was related with FSEvents. `GOARCH` and `CGO_ENABLED` were correctly set as expected but there was an `extldflags` in between who was setting `-target x86_64-apple-macosx`. Applying the correct cross compiling cpu did it. Thanks for the help here, I have the PR open on `bazel-watcher` at this moment!
